apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rendani-M/Api.git
    path: manifests
    targetRevision: HEAD
  destination: 
    server: https://kubernetes.default.svc
    namespace: testApiNS 
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
